include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
  plugins:
    - custom_lint

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    public_member_api_docs: false
    no_default_cases: false
