name: riverpod_boilerplate
description: A flutter boilerplate project with clean architecture including
  riverpod, go_router, dio, etc.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.3.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  path_provider: ^2.0.13
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.1.6
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
